// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    dependencies {
        
        classpath(libs.megatronking.stringfog.gradle)
        classpath(libs.megatronking.stringfog)
   
    }
}

plugins {
    // Plugins automatically generated by TLGradle.kt
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.lalaki.andresguard) apply false
    alias(libs.plugins.gms.google.services) apply false
}

tasks.register<Delete>("clean") {
    delete(rootProject.layout.buildDirectory)
}
