plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    id("com.google.gms.google-services")
    id("AndResGuard")
    id("stringfog")
}

// 导入RandomKeyGenerator类，如果使用HardCodeKeyGenerator，更换下类名
import com.github.megatronking.stringfog.plugin.kg.RandomKeyGenerator
import com.github.megatronking.stringfog.plugin.StringFogMode

stringfog {
    implementation = "com.github.megatronking.stringfog.xor.StringFogImpl"
    //
    enable = true

    fogPackages = arrayOf("com.github.debacodex")

    kg = RandomKeyGenerator()

// 可选（4.0版本新增）：用于控制字符串加密后在字节码中的存在形式, 默认为base64，
    // 也可以使用text或者bytes
    mode = StringFogMode.base64
}

android {
    namespace = "com.github.debacodex"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.github.debacodex"
        minSdk = 23
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }
    packaging {
        resources {
            excludes += arrayOf(
                "DebugProbesKt.bin",
                "kotlin-tooling-metadata.json",
                "kotlin/**",
                "META-INF/*.version",
                "META-INF/**/LICENSE.txt"
            )
        }
        dex {
            useLegacyPackaging = true
        }
        jniLibs {
            useLegacyPackaging = true
        }
    }
    dependenciesInfo {
        includeInApk = false
        includeInBundle = false
    }
    lint {
        checkReleaseBuilds = false
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    signingConfigs {
        create("test") {
            storeFile = file("release.keystore")
            val testPassword = "123456"
            keyAlias = "key0"
            keyPassword = testPassword
            storePassword = testPassword
        }
    }
    
    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            isZipAlignEnabled = true
           // isPseudoLocalesEnabled = true
            signingConfig = signingConfigs.getByName("test")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        
        debug {
            isMinifyEnabled = false
            signingConfig = signingConfigs.getByName("test")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
}

dependencies {
    implementation(platform(libs.google.firebase.bom))
    
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.bumptech.glide)
   // implementation(project(":magicindicator"))
    implementation(libs.volley)
    implementation(libs.google.play.services.auth)
    implementation(libs.magicIndicator)
    implementation(libs.google.firebase.auth)
    implementation(libs.google.firebase.database)
    implementation(libs.google.firebase.messaging)
    implementation(libs.google.firebase.analytics)
    implementation(libs.megatronking.stringfog)
    

}
andResGuard {
    onlyV3V4Sign = false
    delMetaInf = true
    use7zip = false
    useSign = true
    fixedResName = "Nikita"
    mergeDuplicatedRes = true
    
   // sevenzip {
   //      artifact = "cn.lalaki.AndResGuard:SevenZip:1.3.7"
   // }
}